[[main]]
  identifier = "talks"
  name = "Talks"
  url = "talks"
  weight = 1

[[main]]
  identifier = "projects"
  name = "Projects"
  url = "projects"
  weight = 2

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 3
[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 4

[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 5

[[main]]
  identifier = "f"
  name = "Notion in the News"
  url = "notion-in-the-news"
  weight = 6
[[main]]
  identifier = "g"
  name = "Notion Consulting"
  url = "notion-consulting"
  weight = 7

[[main]]
  identifier = "h"
  name = "Product Updates"
  url = "product-updates"
  weight = 8

[[main]]
  identifier = "i"
  name = "Notion Icons"
  url = "notion-icons"
  weight = 9
[[main]]
  identifier = "j"
  name = "The NBA - in Notion"
  url = "the-nba-in-notion"
  weight = 10
